#!/usr/bin/env bash
# script to link sites-enabled to sites-available and start nginx without running status
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start
rm /run/nginx.pid
