#!/usr/bin/env bash
# Parses Apache log files in list format line by line.
#   Groups visitors by IP and HTTP status code and display.

awk '{ print $1 " " $9}' apache-access.log | sort | uniq -c | sort -rn
